version: 2.1

jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: ./gradlew dependencies test
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
  publish:
    parameters:
      channel:
        description: "plugin repository channel to publish to"
        type: enum
        enum: ["EAP", "Stable"]
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: ./gradlew publishPlugin -PpublishPlugin.channels=<< parameters.channel >>

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - publish:
          channel: "EAP"
          requires:
            - test
          filters:
            branches:
              only: /.*-EAP/
      - publish:
          channel: "Stable"
          requires:
            - test
          filters:
            branches:
              only: /.*-stable/
            tags:
              only: /\d+.\d+.\d+/
